# Numpy for creating Multidimentional Arrays

## Visualizations

- Codes

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4, 5])

###### arr

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(5,)

In [6]:
arr.reshape((5,1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
arr1=[1,2,3,4,5]
arr2=[6,2,3,6,9]
arr3=[1,9,3,6,2]

In [8]:
arr=np.array([arr1,arr2,arr3])

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [6, 2, 3, 6, 9],
       [1, 9, 3, 6, 2]])

In [11]:
arr.shape

(3, 5)

In [12]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 6],
       [9, 1, 9],
       [3, 6, 2]])

## Indexing

In [13]:
arr=np.array([1,2,3,4,5])

In [14]:
arr[3]

4

In [15]:
arr=np.array([arr1,arr2,arr3])

In [16]:
arr

array([[1, 2, 3, 4, 5],
       [6, 2, 3, 6, 9],
       [1, 9, 3, 6, 2]])

In [17]:
arr[1:,2:4]

array([[3, 6],
       [3, 6]])

In [18]:
arr[1,1:4]

array([2, 3, 6])

In [19]:
arr[:,3:]

array([[4, 5],
       [6, 9],
       [6, 2]])

In [20]:
arr[1:,:]

array([[6, 2, 3, 6, 9],
       [1, 9, 3, 6, 2]])

In [21]:
arr=np.arange(0,10)

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[3:]=100

In [24]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [25]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [26]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [27]:
arr=np.arange(0,100)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
arr>50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [30]:
arr[arr>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
ar1=np.arange(0,100).reshape(4,25)

In [32]:
ar2=np.arange(0,100).reshape(4,25)

In [33]:
ar1*ar2

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
         121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
         484,  529,  576],
       [ 625,  676,  729,  784,  841,  900,  961, 1024, 1089, 1156, 1225,
        1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116,
        2209, 2304, 2401],
       [2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600,
        3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041,
        5184, 5329, 5476],
       [5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225,
        7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216,
        9409, 9604, 9801]])

In [34]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.random.rand(3,4)

array([[0.99689904, 0.59886474, 0.82070789, 0.00200949],
       [0.06156174, 0.00397396, 0.39743652, 0.62939553],
       [0.69406597, 0.00212916, 0.4518453 , 0.1046232 ]])

In [36]:
np.random.randn(4,4)

array([[ 0.37322912,  0.26200724,  0.08283522, -0.76816642],
       [ 1.55467277, -1.88073376, -0.59294067, -0.39486434],
       [ 1.12788391, -0.2470396 , -0.04787757, -0.97134453],
       [ 0.95311721,  1.34324865,  0.40166793, -1.79517017]])

In [37]:
np.random.randint(0,100,30).reshape(5,6)

array([[38, 29, 39, 10, 65, 51],
       [10, 57, 53, 62, 37, 60],
       [88, 96, 85,  6, 81, 56],
       [60, 10, 14, 53, 14, 11],
       [56, 56, 69, 28, 39, 59]])

In [38]:
np.random.random_sample((1,5))

array([[0.69917465, 0.84769314, 0.52358489, 0.58538606, 0.96676866]])