# Numpy for creating Multidimentional Arrays

## Visualizations

- Codes

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

###### arr

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [7]:
arr.reshape((5,1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
arr1=[1,2,3,4,5]
arr2=[6,2,3,6,9]
arr3=[1,9,3,6,2]

In [11]:
arr=np.array([arr1,arr2,arr3])

In [12]:
arr

array([[1, 2, 3, 4, 5],
       [6, 2, 3, 6, 9],
       [1, 9, 3, 6, 2]])

In [13]:
arr.shape

(3, 5)

In [15]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 6],
       [9, 1, 9],
       [3, 6, 2]])

## Indexing

In [36]:
arr=np.array([1,2,3,4,5])

In [37]:
arr[3]

4

In [38]:
arr=np.array([arr1,arr2,arr3])

In [39]:
arr

array([[1, 2, 3, 4, 5],
       [6, 2, 3, 6, 9],
       [1, 9, 3, 6, 2]])

In [40]:
arr[1:,2:4]

array([[3, 6],
       [3, 6]])

In [41]:
arr[1,1:4]

array([2, 3, 6])

In [42]:
arr[:,3:]

array([[4, 5],
       [6, 9],
       [6, 2]])

In [43]:
arr[1:,:]

array([[6, 2, 3, 6, 9],
       [1, 9, 3, 6, 2]])

In [44]:
arr=np.arange(0,10)

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[3:]=100

In [48]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [49]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [50]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [66]:
arr=np.arange(0,100)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [68]:
arr>50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [71]:
arr[arr>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [75]:
ar1=np.arange(0,100).reshape(4,25)

In [76]:
ar2=np.arange(0,100).reshape(4,25)

In [77]:
ar1*ar2

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
         121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
         484,  529,  576],
       [ 625,  676,  729,  784,  841,  900,  961, 1024, 1089, 1156, 1225,
        1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116,
        2209, 2304, 2401],
       [2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600,
        3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041,
        5184, 5329, 5476],
       [5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225,
        7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216,
        9409, 9604, 9801]])

In [80]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
np.random.rand(3,4)

array([[0.40318872, 0.84627165, 0.19793018, 0.4595998 ],
       [0.07604951, 0.6916573 , 0.68257692, 0.9597948 ],
       [0.6139082 , 0.14605504, 0.23477883, 0.62071559]])

In [83]:
np.random.randn(4,4)

array([[-0.50031073, -0.19806299,  0.24514836,  1.01935739],
       [ 1.06993606,  0.40862547,  1.60753924,  0.10883573],
       [ 0.90398774,  0.15914685,  2.33664486, -1.24630566],
       [ 0.21285617,  0.36330027,  0.34176333,  1.38231327]])

In [87]:
np.random.randint(0,100,30).reshape(5,6)

array([[33, 66, 37,  1, 24,  3],
       [24, 82, 66, 76, 69, 74],
       [66, 93, 74, 98, 66,  3],
       [44, 54, 35, 43, 41, 11],
       [61, 61, 41,  7, 86, 83]])

In [88]:
np.random.random_sample((1,5))

array([[0.75479687, 0.46127879, 0.79962772, 0.35259999, 0.67002309]])